import{S as A,i as n}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function h(a){const r=document.querySelector(".images-container"),s=a.map(({largeImageURL:e,webformatURL:t,tags:i,likes:m,views:g,comments:d,downloads:f})=>`<div class="image-card">
    <div class="image">
      <a href="${e}">
      <img class="gallery-image" src="${t}" alt="${i}"/>
      </a>
   </div>
   <ul class="stats">
      <li class="stats-name">Likes<p class="numbers">${m}</p></li>
      <li class="stats-name">Views<p class="numbers">${g}</p></li>
      <li class="stats-name">Comments<p class="numbers">${d}</p></li>
      <li class="stats-name">Downloads<p class="numbers">${f}</p></li>
    </ul></div>`).join("");r.insertAdjacentHTML("beforeend",s),new A(".images-container a",{captionsData:"alt"}).refresh()}function p(a){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"42585608-470f45864f44da3a6987e4378",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(s).then(o=>{if(!o.ok)throw new Error(o.statusText);return o.json()})}const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAONJREFUSIm9lkESgyAMRT+dOhyr3kw9WdtjJVmkiw4OKgGU0sy4keT9MPiDgBFEMjOL1jxEMlucuwV3DhOAlyreVnEI5zARCbwfTKFD57muLtdcgVfXtsCLjF/ATVYOLiJjCZjK2TBz8NKuAiglwixPZlFT4NDJibV4PStggWrOLOQkjRaH98NMJKuZgK+xVLHUGKsosBcBgFo4ANxqklqiagdhNqliAc7NnqJADA/A+EyKIn/5TJnluU9oNdoq0H1UJF80RNeJ2vVO6Hqr5WoOPkjNnlw4hweA8cz42HTV+tvyAUq6NbiLrn50AAAAAElFTkSuQmCC",u=document.querySelector(".form"),y=document.querySelector(".images-container"),c=document.querySelector("span");u.addEventListener("submit",b);function b(a){a.preventDefault(),y.innerHTML=null;const r=u.input.value.trim();r?(c.classList.add("loader"),p(r).then(({hits:s})=>{s.length||n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:l,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),h(s),c.classList.remove("loader")})):n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:l,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1})}
//# sourceMappingURL=commonHelpers.js.map
